ADSAP/ADSAP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('home/', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('RH/', include("RH.urls")),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADSAP/RH/urls.py
from django.urls import path
from RH import views

app_name = "RH"

urlpatterns = [
    path('empleados/', views.Empleados.as_view(), name="empleados"),
    path('empleados/crea', views.Crea_Empleados.as_view(), name="crea_empleados"),
    path('empleados/crea/<int:user_id>/', views.Crea_Empleados2.as_view(), name="crea_empleados2"),
    path('empleados/editar/', views.Edita_Empleados_Busqueda.as_view(), name="editar_empleado_busqueda"),
    path('empleados/editar/<int:pk>/', views.Empleado_Detalles.as_view(), name='editar_empleados_list'),
    path('empleados/editar/empleado/<int:pk>/', views.Edita_Empleados.as_view(), name='editar_empleado'),
    path('empleados/editar/filtro/', views.Edita_Empleados_List.as_view(), name='empleado_busqueda'),
    path('empleados/editar/empleado/eliminar/<int:pk>/', views.Elimina_Empleados.as_view(), name='eliminar_empleado'),
    path('administra_vacaciones/', views.Vacaciones_Busqueda.as_view(), name="vacaciones_busqueda"),
    path('administra_vacaciones/estado/<int:pk>/', views.Edita_Vacaciones.as_view(), name="vacaciones_estado"),
    path('administra_vacaciones/filtro/', views.searchVacaciones, name="vacaciones_filtro"),
    path('administra_permisos/', views.Permisos_Busqueda.as_view(), name="permisos_busqueda"),
    path('administra_permisos/estado/<int:pk>/', views.Edita_Permisos.as_view(), name="permisos_estado"),
    path('administra_permisos/filtro/', views.searchPermisos, name="permisos_filtro"),
    path('administra_noticas/', views.Noticias.as_view(), name="noticias"),
    path('administra_noticas/crea/', views.Crea_Noticias.as_view(), name="crea_noticias"),
    path('administra_noticas/lista/', views.ListarNoticias.as_view(), name="lista_noticias"),
    path('administra_noticas/detalle/<int:pk>/', views.DetallesNoticia.as_view(), name="detalles_noticias"),
    path('administra_noticas/editar/<int:pk>/', views.Edita_Noticias.as_view(), name="editar_noticias"),
    path('administra_noticas/eliminar/<int:pk>/', views.Elimina_Noticia.as_view(), name="eliminar_noticias"),
    path('administra_noticas/lista/filtro/', views.searchNoticias, name="noticias_filtro"),
    path('administra_faqs/', views.Preguntas.as_view(), name="faqs"),
    path('administra_faqs/crea/', views.Crea_Preguntas.as_view(), name="crea_faqs"),
    path('administra_faqs/lista/', views.ListarPreguntas.as_view(), name="lista_faqs"),
    path('administra_faqs/detalle/<int:pk>/', views.DetallesPregunta.as_view(), name="detalles_faqs"),
    path('administra_faqs/editar/<int:pk>/', views.Edita_Preguntas.as_view(), name="editar_faqs"),
    path('administra_faqs/eliminar/<int:pk>/', views.Elimina_Pregunta.as_view(), name="eliminar_faqs"),
    path('administra_faqs/lista/filtro/', views.searchPreguntas, name="faqs_filtro"),
    path('administra_incapacidades/', views.Incapacidades.as_view(), name="incapacidades"),
    path('administra_incapacidades/detalle/<int:pk>/', views.Incapacidades_Detalles.as_view(), name="incapacidad_detalle"),
    path('administra_incapacidades/filtro/', views.searchIncapacidades, name="busqueda_incapacidades"),
    path('tabla_nominas/', views.crea_semana_nominas, name='crea_semana'),
    path('reportes/actualiza/<int:pk>/', views.Edita_Reportes.as_view(), name='reportes_actualiza'),
]

ADSAP/core/urls.py
from django.urls import path, re_path
from core import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "core"

urlpatterns = [
    path('faq/', views.Preguntas.as_view(), name="faq"),
    path('faq/filtro', views.searchPreguntas, name="faq_filter"),
    path('noticias/', views.Noticias.as_view(), name="noticias"),
    path('noticias/filtro', views.searchNoticias, name="noticias_filter"),
    path('datos_personales', views.Datos_Personales.as_view(), name="datos_personales"),
    path('vacaciones', views.Vacaciones.as_view(), name="vacaciones"),
    path('vacaciones/filtro', views.searchVacaciones, name="vacaciones_filter"),
    path('vacaciones/solicitud', views.Vacaciones_Form, name="vacaciones_solicitud"),
    path('vacaciones/solicitud/confirmacion', views.Vacaciones_Confirmacion.as_view(), name="vacaciones_confirmacion"),
    path('vacaciones/solicitud/estado/<int:pk>/', views.Vacaciones_Estado.as_view(), name="vacaciones_estado"),
    path('vacaciones/solicitud/eliminar/<int:pk>/', views.Vacaciones_Eliminacion.as_view(), name="vacaciones_eliminar_confirmacion"),
    path('permisos', views.Permisos.as_view(), name="permisos"),
    path('permisos/solicitud', views.Permisos_Form, name="permisos_solicitud"),
    path('permisos/solicitud/confirmacion', views.Permisos_Confirmacion.as_view(), name="permisos_confirmacion"),
    path('permisos/solicitud/estado/<int:pk>/', views.Permisos_Estado.as_view(), name="permisos_estado"),
    path('permisos/solicitud/eliminar/<int:pk>/', views.Permisos_Eliminacion.as_view(), name="permisos_eliminar_confirmacion"),
    path('permisos/filtro', views.searchPermisos, name="permisos_filter"),
    path('incapacidades', views.Incapacidades.as_view(), name="incapacidades"),
    path('incapacidades/detalle/<int:pk>/', views.Incapacidades_Detalles.as_view(), name="incapacidad_detalle"),
    path('incapacidades/solicitud', views.Incapacidades_Form, name="incapacidades_solicitud"),
    path('incapacidades/filtro', views.searchIncapacidades, name="incapacidades_filter"),
    path('reporte_error', views.Reportes.as_view(), name="reporte_error"),
    path('reporte_error/genera', views.Genera_Reporte.as_view(), name="genera_reporte"),
    path('reporte_error/lista/', views.Lista_Reportes.as_view(), name="reporte_lista"),
    path('reporte_error/detalle/<int:pk>/', views.Reporte_Estado.as_view(), name="reporte_detalle"),
    path('reporte_error/lista/filtro/', views.searchReportes, name="reporte_filtro"),
    path('nominas/', views.Nominas.as_view(), name="nominas"),
    path('nominas/filtro', views.searchNominas, name="nominas_filter"),
    path('nominas/detalle/<int:pk>/', views.Nominas_Detalle.as_view(), name="nomina_detalle"),
    path('nominas/nomina_pdf/<int:nomina_id>/', views.generar_reporte_pdf, name='generar_reporte_nomina'),
    




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADSAP/templates/cuenta.html
{% extends 'base/base.html'%}

{% block title %} CUENTA {% endblock title %}

{% block content %}

    <h1>CUENTA</h1>
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Log out</button>
    </form>
{% endblock content %}

ADSAP/templates/datos_personales.html
{% extends 'base/base.html'%}
{% block title %}Datos Personales{% endblock title %}
{% block content %}
<style>
  body {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 20px;
    padding-left: 25px;
    padding-right: 25px;
    width: 1300px;
    margin-left: 150px;
    display: block;
  }

  .Tittle {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Foto {
    margin-top: 20px;
    height: 230px;
    width: 230px;
    margin-left: auto;
    margin-right: auto;
    display: block;
  }

  .Nombre {
    font-size: 2em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Area {
    font-size: 1.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Puesto {
    font-size: 1.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 10;
  }

  .Datos {
    font-size: 1.8em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .DatosUsuario {
    font-size: 24px;
    color: #000000;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="Tittle">Datos personales</p>
    {% if empleado.sexo == "M" %}
    <img class="Foto" src="https://cdn-icons-png.flaticon.com/256/1896/1896513.png">
    {% else %}
    <img class="Foto" src="https://cdn-icons-png.flaticon.com/256/1896/1896516.png">
    {% endif %}
    <p class="Nombre">{{ empleado.nombre }} {{ empleado.apellido_paterno }} {{empleado.apellido_materno }}</p>
    <p class="Area">{{ empleado.area }}</p>
    <p class="Puesto">{{ empleado.puesto }}</p>

    <p class="Datos">Fecha de nacimiento: <span class="DatosUsuario">{{ empleado.fecha_nacimiento }}</span> </p>
    <p class="Datos">Lugar de nacimiento: <span class="DatosUsuario">{{ empleado.municipio}},</span> <span
        class="DatosUsuario">{{ empleado.estado }}</span> </p>
    <p class="Datos">RFC: <span class="DatosUsuario">{{ empleado.rfc }}</span></p>
    <p class="Datos">CURP: <span class="DatosUsuario">{{ empleado.curp }}</span></p>
    <p class="Datos">NSS: <span class="DatosUsuario">{{ empleado.nss }}</span></p>
    <p class="Datos">Dirección: <span class="DatosUsuario">{{ empleado.calle }} #{{ empleado.numero_casa }}, {{empleado.colonia}} CP: {{empleado.cp }}</span></p>
    <p class="Datos">Teléfono de contacto: <span class="DatosUsuario">{{ empleado.telefono }}</span></p>
  </div>

</body>
{% endblock content %}

ADSAP/templates/faq.html
{% extends 'base/base.html'%}
{% block title %}Preguntas frecuentes{% endblock title %}
{% block content %}
<style>
  body {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 20px;
    padding-left: 25px;
    padding-right: 25px;
    width: 1300px;
    margin-left: 150px;
    display: block;
  }

  .Filtro {
    padding-bottom: 20px;
  }

  .form-control {
    padding: 20px;
    font-size: 1.5em;
    font-family: 'ZCOOL QingKe HuangYou';
  }

  .TittleADSAP {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Sub {
    font-size: 2.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: center;
  }

  .accordion-button {
    font-size: 0.8em;
    background-color: #fff;
  }

  .accordion-body {
    font-size: 1.5em;
    text-align: justify;
    display: inline-block;
  }

  .accordion-collapse {
    padding-bottom: 10px;
  }

  .btn {
    background-color: #003366;
    border-color: #003366;
    font-size: 1.5em;
  }

  .imgpregunta {
    float: left;
    margin-right: 20px;
    height: 150px;
    width: 150px;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="TittleADSAP">ADSAP</p>
    <p class="Sub">¿En qué podemos ayudarte?</p>
    <div class="Filtro">
      <form action="filtro" method="get">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Buscar pregunta" name="busqueda"
            style="background-color: #fff;">
          <button type="submit" class="btn btn-primary" data-mdb-ripple-init>
            <i class="fas fa-search"></i>
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search"
              viewBox="0 0 16 16">
              <path
                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
            </svg>
          </button>
        </div>
      </form>
    </div>
    <div>
      {% for pregunta in preguntas %}
      <div class="accordion" id="accordionExample">
        <div class="accordion-item mb-1">
          <h2 class="accordion-header" id="heading{{ forloop.counter }}">
            <button class="accordion-button collapsed mb" type="button" data-bs-toggle="collapse"
              data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseThree">
              {{ pregunta.pregunta }}
            </button>
          </h2>
          <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse"
            aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              {% if pregunta.imagen %}
              <img class="imgpregunta" src="{{ pregunta.imagen.url }}">
              {% else %}
              {% endif %}
              {{ pregunta.respuesta }}
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
</body>
{% endblock content %}

ADSAP/templates/faq_filter.html
{% extends 'base/base.html'%}
{% block title %}Preguntas frecuentes{% endblock title %}
{% block content %}
<style>
  body {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 20px;
    padding-left: 25px;
    padding-right: 25px;
    width: 1300px;
    margin-left: 150px;
    display: block;
  }

  .Filtro {
    padding-bottom: 20px;
  }

  .form-control {
    padding: 20px;
    font-size: 1.5em;
    font-family: 'ZCOOL QingKe HuangYou';
  }

  .TittleADSAP {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Sub {
    font-size: 2.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: center;
  }

  .accordion-button {
    font-size: 0.8em;
  }

  .accordion-body {
    font-size: 1.5em;
    text-align: justify;
    display: inline-block;
  }

  .accordion-collapse {
    padding-bottom: 10px;
  }

  .btn {
    background-color: #003366;
    border-color: #003366;
    font-size: 1.5em;
  }

  .Respuestas {
    padding-bottom: 20px;
  }

  .imgpregunta {
    float: left;
    margin-right: 20px;
    height: 150px;
    width: 150px;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="TittleADSAP">ADSAP</p>
    <p class="Sub">¿En qué podemos ayudarte?</p>
    <div class="Filtro">
      <form action="filtro" method="get">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Buscar pregunta" name="busqueda">
          <button type="submit" class="btn btn-primary" data-mdb-ripple-init>
            <i class="fas fa-search"></i>
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search"
              viewBox="0 0 16 16">
              <path
                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
            </svg>
          </button>
        </div>
      </form>
    </div>
    <div class="Respuestas">
      {% for pregunta in preguntasAB %}
      <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading{{ forloop.counter }}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
              data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseThree">
              {{ pregunta.pregunta }}
            </button>
          </h2>
          <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse"
            aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              {% if pregunta.imagen %}
              <img class="imgpregunta" src="{{ pregunta.imagen.url }}">
              {% else %}
              {% endif %}
              {{ pregunta.respuesta }}
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <a class="btn btn-primary py-2 Btn1" type="" href="{% url 'core:faq' %}">Volver a preguntas frecuentes</a>
</body>
{% endblock content %}

ADSAP/templates/index.html
{% extends 'base/base.html'%}

{% block title %}INICIO{% endblock title %}
{% block content %}
<style>
  body {
    background-color: #fff;
  }

  .bd-radius {
    border-radius: 15px;
  }

  h2 {
    text-align: center;
  }

  .col-lg-4 {
    flex: 0 0 auto;
    width: 33.333333%;
  }

  .row {
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
    gap: 4rem;
  }

  .col-lg-4 {
    flex: 0 0 auto;
    width: auto;
  }

  .col-lg-4 {
    flex: 0 0 auto;
    width: auto;
  }

  .btn {
    margin-top: 20px;
    margin-bottom: 20px;
    background-color: #004c9759;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .btn:hover {
    background-color: #004b97b7;
  }

  .btn-image {
    display: inline-block;
    padding: 0;
    width: 300px;
    height: 210px;
    text-align: center;
    color: black;
    font-family: 'Arial', sans-serif;
    font-weight: bold;
    border-radius: 15px;
  }

  .btn-image img {
    width: 150px;
    height: 150px;
    object-fit: contain;
    margin-top: 15px;
    margin-bottom: 0px;
  }

  .btn-image span {
    display: block;
    margin-top: 10px;
  }
</style>

<body>

  {% if es_rh %} 
    <p>Eres miembro del grupo Personal RH.</p>
  {% else %}
  <h2
  style="font-size: 70px; margin-top: 6rem; margin-bottom: 3rem; color:#003366; font-family: 'ZCOOL QingKe HuangYou'; font-weight: bold;">
  ¡Bienvenido a ADSAP!</h2>
<div class="container marketing">
  <div class="row">
    <div class="col-lg-4">
      <p>
        <a class="btn btn-secondary btn-image" href="{% url 'core:datos_personales' %}">
          <img src="https://cdn-icons-png.flaticon.com/256/1077/1077063.png" alt="Datos Personales">
          <span style="margin-top: -2px; font-size: 1.7em; font-weight: bold;">Datos Personales</span>
        </a>
      </p>
    </div>
    <div class="col-lg-4">
      <p>
        <a class="btn btn-secondary btn-image" href="{% url 'core:vacaciones' %}">
          <img src="https://cdn-icons-png.flaticon.com/256/1831/1831534.png" alt="Vacaciones">
          <span style="margin-top: -2px; font-size: 1.7em; font-weight: bold;">Vacaciones</span>
        </a>
      </p>
    </div>
    <div class="col-lg-4">
      <p>
        <a class="btn btn-secondary btn-image" href="{% url 'core:permisos' %}">
          <img src="https://cdn-icons-png.flaticon.com/256/2284/2284211.png" alt="Permisos">
          <span style="margin-top: -2px; font-size: 1.7em; font-weight: bold;">Permisos</span>
        </a>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4">
      <p>
        <a class="btn btn-secondary btn-image" href="{% url 'core:incapacidades' %}">
          <img src="https://cdn-icons-png.flaticon.com/256/4540/4540514.png" alt="Incapacidades">
          <span style="margin-top: -2px; font-size: 1.7em; font-weight: bold;">Incapacidades</span>
        </a>
      </p>
    </div>
    <div class="col-lg-4">
      <p>
        <a class="btn btn-secondary btn-image" href="{% url 'core:noticias' %}">
          <img src="https://cdn-icons-png.flaticon.com/256/2886/2886141.png" alt="Noticias">
          <span style="margin-top: -2px; font-size: 1.7em; font-weight: bold;">Noticias</span>
        </a>
      </p>
    </div>
    <div class="col-lg-4">
      <p>
        <a class="btn btn-secondary btn-image" href="{% url 'core:nominas' %}">
          <img src="https://cdn-icons-png.flaticon.com/256/8290/8290972.png" alt="Nomina">
          <span style="margin-top: -2px; font-size: 1.7em; font-weight: bold;">Nomina</span>
        </a>
      </p>
    </div>
  </div>
</div>

  {% endif %}


  </body>

{% endblock content %}

ADSAP/templates/noticia_filter.html
{% extends 'base/base.html'%}
{% block title %}Preguntas frecuentes{% endblock title %}
{% block content %}
<style>
  body {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 20px;
    padding-left: 25px;
    padding-right: 25px;
    width: 1300px;
    margin-left: 150px;
    display: block;
  }

  .Filtro {
    padding-bottom: 20px;
  }

  .form-control {
    padding: 20px;
    font-size: 1.5em;
    font-family: 'ZCOOL QingKe HuangYou';
  }

  .TittleADSAP {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Sub {
    font-size: 2.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: center;
  }

  .accordion-button {
    font-size: 0.8em;
  }

  .accordion-body {
    font-size: 1.5em;
    text-align: justify;
    display: inline-block;
  }

  .accordion-collapse {
    padding-bottom: 10px;
  }

  .btn {
    background-color: #003366;
    border-color: #003366;
    font-size: 1.5em;
  }

  .Respuestas {
    padding-bottom: 20px;
  }

  img {
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    height: 150px;
    width: 150px;
    display: block;
    padding-bottom: 10px;
  }

  .imgnoticia {
    float: left;
    margin-right: 20px;
    height: 150px;
    width: 150px;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="TittleADSAP">ADSAP</p>
    <img src="https://cdn-icons-png.flaticon.com/256/1074/1074106.png">
    <p class="Sub">Noticias de la empresa</p>
    <div class="Filtro">
      <form action="filtro" method="get">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Buscar noticia" name="busquedaNoticia">
          <button type="submit" class="btn btn-primary" data-mdb-ripple-init>
            <i class="fas fa-search"></i>
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search"
              viewBox="0 0 16 16">
              <path
                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
            </svg>
          </button>
        </div>
      </form>
    </div>
    <div class="Respuestas">
      {% for noticia in noticiasAB %}
      <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading{{ forloop.counter }}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
              data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseThree">
              {{ noticia.titulo }}
            </button>
          </h2>
          <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse"
            aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              {% if noticia.imagen %}
              <img class="imgnoticia" src="{{ noticia.imagen.url }}">
              {% else %}
              {% endif %}
              {{ noticia.contenido }}
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <a class="btn btn-primary py-2 Btn1" href="{% url 'core:noticias' %}">Volver a noticias</a>
</body>
{% endblock content %}