ADSAP/ADSAP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('home/', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('RH/', include("RH.urls")),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADSAP/RH/urls.py
from django.urls import path
from RH import views

app_name = "RH"

urlpatterns = [
    path('empleados/', views.Empleados.as_view(), name="empleados"),
    path('empleados/crea', views.Crea_Empleados.as_view(), name="crea_empleados"),
    path('empleados/crea/<int:user_id>/', views.Crea_Empleados2.as_view(), name="crea_empleados2"),
    path('empleados/editar/', views.Edita_Empleados_Busqueda.as_view(), name="editar_empleado_busqueda"),
    path('empleados/editar/<int:pk>/', views.Empleado_Detalles.as_view(), name='editar_empleados_list'),
    path('empleados/editar/empleado/<int:pk>/', views.Edita_Empleados.as_view(), name='editar_empleado'),
    path('empleados/editar/filtro/', views.Edita_Empleados_List.as_view(), name='empleado_busqueda'),
    path('empleados/editar/empleado/eliminar/<int:pk>/', views.Elimina_Empleados.as_view(), name='eliminar_empleado'),
    path('administra_vacaciones/', views.Vacaciones_Busqueda.as_view(), name="vacaciones_busqueda"),
    path('administra_vacaciones/estado/<int:pk>/', views.Edita_Vacaciones.as_view(), name="vacaciones_estado"),
    path('administra_vacaciones/filtro/', views.searchVacaciones, name="vacaciones_filtro"),
    path('administra_permisos/', views.Permisos_Busqueda.as_view(), name="permisos_busqueda"),
    path('administra_permisos/estado/<int:pk>/', views.Edita_Permisos.as_view(), name="permisos_estado"),
    path('administra_permisos/filtro/', views.searchPermisos, name="permisos_filtro"),
    path('administra_noticas/', views.Noticias.as_view(), name="noticias"),
    path('administra_noticas/crea/', views.Crea_Noticias.as_view(), name="crea_noticias"),
    path('administra_noticas/lista/', views.ListarNoticias.as_view(), name="lista_noticias"),
    path('administra_noticas/detalle/<int:pk>/', views.DetallesNoticia.as_view(), name="detalles_noticias"),
    path('administra_noticas/editar/<int:pk>/', views.Edita_Noticias.as_view(), name="editar_noticias"),
    path('administra_noticas/eliminar/<int:pk>/', views.Elimina_Noticia.as_view(), name="eliminar_noticias"),
    path('administra_noticas/lista/filtro/', views.searchNoticias, name="noticias_filtro"),
    path('administra_faqs/', views.Preguntas.as_view(), name="faqs"),
    path('administra_faqs/crea/', views.Crea_Preguntas.as_view(), name="crea_faqs"),
    path('administra_faqs/lista/', views.ListarPreguntas.as_view(), name="lista_faqs"),
    path('administra_faqs/detalle/<int:pk>/', views.DetallesPregunta.as_view(), name="detalles_faqs"),
    path('administra_faqs/editar/<int:pk>/', views.Edita_Preguntas.as_view(), name="editar_faqs"),
    path('administra_faqs/eliminar/<int:pk>/', views.Elimina_Pregunta.as_view(), name="eliminar_faqs"),
    path('administra_faqs/lista/filtro/', views.searchPreguntas, name="faqs_filtro"),
    path('administra_incapacidades/', views.Incapacidades.as_view(), name="incapacidades"),
    path('administra_incapacidades/detalle/<int:pk>/', views.Incapacidades_Detalles.as_view(), name="incapacidad_detalle"),
    path('administra_incapacidades/filtro/', views.searchIncapacidades, name="busqueda_incapacidades"),
    path('tabla_nominas/', views.crea_semana_nominas, name='crea_semana'),
    path('reportes/actualiza/<int:pk>/', views.Edita_Reportes.as_view(), name='reportes_actualiza'),
]

ADSAP/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('home/', views.Home.as_view(), name="home"),
    path('cuenta/', views.Cuenta.as_view(), name="cuenta"),

]

ADSAP/RH/models.py
from django.db import models

# Create your models here.

ADSAP/RH/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.http import HttpResponse, HttpResponseForbidden
from core import models 
from users import models as users_models
from RH import forms
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import Group
from datetime import datetime
from django.shortcuts import render, redirect
from .forms import NominaForm
# Create your views here.

@method_decorator(login_required, name='dispatch')
class Empleados(LoginRequiredMixin, generic.View):
    def get(self, request):
 
        if request.user.groups.filter(name='Personal RH').exists():
            return render(request, "RH/Empleados/empleados.html", {})

        return HttpResponseForbidden("No estás autorizado para ver esta página.")
    
@method_decorator(login_required, name='dispatch')
class Crea_Empleados(LoginRequiredMixin, generic.CreateView):
    model = users_models.CustomUser
    form_class = forms.Crea_Empleado_Form
    template_name = "RH/Empleados/crea_empleados2.html"

    def get_success_url(self):
        return reverse_lazy("RH:crea_empleados2", args=[self.object.id])
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name='Personal RH').exists():
            return HttpResponseForbidden("No estás autorizado para ver esta página.")
        return super().dispatch(request, *args, **kwargs)
    
@method_decorator(login_required, name='dispatch')
class Crea_Empleados2(LoginRequiredMixin, generic.CreateView):
    model = models.EMPLEADO
    form_class = forms.Crea_Empleado_Form2
    template_name = "RH/Empleados/crea_empleados2.html"
    success_url = reverse_lazy("RH:empleados")

    def get_initial(self):
        initial = super().get_initial()
        user_id = self.kwargs.get('user_id')  
        initial['usuario'] = user_id
        return initial

    def form_valid(self, form):
        form.instance.usuario_id = self.kwargs.get('user_id')
        return super().form_valid(form)
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name='Personal RH').exists():
            return HttpResponseForbidden("No estás autorizado para ver esta página.")
        return super().dispatch(request, *args, **kwargs)
    
@method_decorator(login_required, name='dispatch')
class Edita_Empleados(LoginRequiredMixin, generic.UpdateView):
    model = models.EMPLEADO
    form_class = forms.Crea_Empleado_Form2 
    template_name = "RH/Empleados/edita_empleado.html"
    success_url = reverse_lazy("RH:empleados")
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name='Personal RH').exists():
            return HttpResponseForbidden("No estás autorizado para ver esta página.")
        return super().dispatch(request, *args, **kwargs)
    

@method_decorator(login_required, name='dispatch')
class Edita_Empleados_Busqueda(LoginRequiredMixin, generic.View):
    template_name = "RH/Empleados/edita_empleados_list.html"
    context = {}

    def get(self, request):
        grupo_emp = Group.objects.get(name='Empleados')
        empleados = models.EMPLEADO.objects.filter(usuario__groups=grupo_emp)
        self.context = {
            "empleados" : empleados
        }
        return render(request, self.template_name, self.context)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name='Personal RH').exists():
            return HttpResponseForbidden("No estás autorizado para ver esta página.")
        return super().dispatch(request, *args, **kwargs)


class EmpleadoMixin:
    def buscaEmpleado(self, numero_empleado):
        try:
            usuario = users_models.CustomUser.objects.get(numero_empleado=numero_empleado)
            empleado = models.EMPLEADO.objects.get(usuario=usuario)
            return empleado
        except ObjectDoesNotExist:
            return None

@method_decorator(login_required, name='dispatch')
class Edita_Empleados_List(LoginRequiredMixin, EmpleadoMixin, generic.View):
    
    def get(self, request, *args, **kwargs):
        if not request.user.groups.filter(name='Personal RH').exists():
            return HttpResponseForbidden("No estás autorizado para ver esta página.")
        
        empleadoAB = request.GET.get('busquedaEmpleado')
        empleado = self.buscaEmpleado(empleadoAB)
        try: 
            usuario = users_models.CustomUser.objects.get(numero_empleado=empleadoAB)
        except ObjectDoesNotExist:
            usuario = None
            
        if empleado:
            return render(request, "RH/Empleados/empleado_busqueda.html", {"empleado": empleado, "usuario": usuario})
        else:
            return HttpResponse('Empleado no encontrado', status=404)

class Empleado_Detalles(LoginRequiredMixin, generic.View):
    template_name = "RH/Empleados/empleado_filter.html"
    context = {}

    def get(self, request, pk):
        usuario = users_models.CustomUser.objects.get(numero_empleado=pk)
        self.context = {
            
            "empleado" : models.EMPLEADO.objects.get(usuario=usuario)
        }
        return render(request, self.template_name, self.context)

@method_decorator(login_required, name='dispatch')
class Elimina_Empleados(LoginRequiredMixin, generic.DeleteView):
    model = users_models.CustomUser
    template_name = "RH/Empleados/empleado_eliminado_confirmacion.html"
    success_url = reverse_lazy("RH:empleados")
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name='Personal RH').exists():
            return HttpResponseForbidden("No estás autorizado para ver esta página.")
        return super().dispatch(request, *args, **kwargs)

    
@method_decorator(login_required, name='dispatch')
class Vacaciones_Busqueda(LoginRequiredMixin, generic.View):
    template_name = "RH/Vacaciones/vacaciones_busqueda.html"
    context = {}

    def get(self, request):
        resultados = models.ESTADO_SOLICITUD.objects.filter(id_vacaciones__isnull=False)
        resultados_revision = resultados.filter(estado="En revision")
        vacaciones = [estado.id_vacaciones for estado in resultados_revision]
        self.context = {
            "resultados": resultados_revision,
            "vacaciones": vacaciones
        }
        return render(request, self.template_name, self.context)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name='Personal RH').exists():
            return HttpResponseForbidden("No estás autorizado para ver esta página.")
        return super().dispatch(request, *args, **kwargs)
    
    
@method_decorator(login_required, name='dispatch')
class Edita_Vacaciones(LoginRequiredMixin, generic.UpdateView):
    model = models.ESTADO_SOLICITUD
    form_class = forms.EstadoSolicitudForm 
    template_name = "RH/Vacaciones/vacaciones_estado.html"
    success_url = reverse_lazy("RH:vacaciones_busqueda")

    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name='Personal RH').exists():
            return HttpResponseForbidden("No estás autorizado para ver esta página.")
        return super().dispatch(request, *args, **kwargs)

@login_required
def searchVacaciones(request, *args, **kwargs):
    
    if request.method == 'GET':
        resultados = models.ESTADO_SOLICITUD.objects.filter(id_vacaciones__isnull=False)
        resultados_revision = resultados.filter(estado="En revision")
        vacaciones = [estado.id_vacaciones for estado in resultados_revision] 
        

        vacacionesAB = request.GET.get('busquedaVacacion').lower()
           
        month_mapping = {
        'enero': 1, 'febrero': 2, 'marzo': 3, 'abril': 4, 'mayo': 5,
        'junio': 6, 'julio': 7, 'agosto': 8, 'septiembre': 9,
        'octubre': 10, 'noviembre': 11, 'diciembre': 12
        }
        month_number = str(month_mapping.get(vacacionesAB, 0)) 

        filtered_vacations = []
        filtered_solicitudes = []

        for vacacion in vacaciones:
            if str(vacacion.fecha_inicio.month) == month_number:
                filtered_vacations.append(vacacion)
                filtered_solicitudes.append(models.ESTADO_SOLICITUD.objects.get(id_vacaciones=vacacion.id))
   
        if month_number:
            results = filtered_vacations
            solicitudes = filtered_solicitudes
        else:
            results = models.VACACIONES.objects.none() 

        return render(request, "RH/Vacaciones/vacaciones_filter.html", {"vacaciones": solicitudes})


@method_decorator(login_required, name='dispatch')
class Permisos_Busqueda(LoginRequiredMixin, generic.View):
    template_name = "RH/Permisos/permisos_busqueda.html"
    context = {}

    def get(self, request):
        resultados = models.ESTADO_SOLICITUD.objects.filter(id_permiso__isnull=False)
        resultados_revision = resultados.filter(estado="En revision")

        self.context = {
            "resultados": resultados_revision,
        }
        return render(request, self.template_name, self.context)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.groups.filter(name='Personal RH').exists():
            return HttpResponseForbidden("No estás autorizado para ver esta página.")
        return super().dispatch(request, *args, **kwargs)
    
@method_decorator(login_required, name='dispatch')
class Edita_Permisos(LoginRequiredMixin, generic.UpdateView):
    model = models.ESTADO_SOLICITUD
    form_class = forms.EstadoSolicitudForm 
    template_name = "RH/Permisos/permisos_estado.html"

ADSAP/templates/RH/Noticias/noticia_detalle.html
{% extends 'base/base.html'%}
{% block title %}Opciones{% endblock title %}
{% block content %}
<style>
  .background {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 150px;
    padding-left: 25px;
    padding-right: 25px;
    width: 900px;
    margin-left: 400px;
    display: block;
  }

  .Tittle {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 10px;
  }

  .Sub {
    font-size: 1.5em;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: justify;
    margin-bottom: 10px;
  }

  .BtnEditar {
    background-color: #009c0d;
    border-color: #009c0d;
    color: #fff;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnEditar:hover {
    background-color: #006909;
    color: #fff;
  }

  .BtnEliminar {
    background-color: red;
    border-color: red;
    color: #fff;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnEliminar:hover {
    background-color: rgb(141, 0, 0);
    color: #fff;
  }

  .BtnCancelar {
    background-color: orange;
    border-color: orange;
    color: #fff;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnCancelar:hover {
    background-color: rgb(146, 95, 0);
    color: #fff;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="Tittle">{{ noticia.titulo }}</p>
    <p class="Sub">{{ noticia.contenido }}</p>
    <br>
    <div class="row">
      <div class="col">
        <a href="{% url 'RH:editar_noticias' pk=noticia.id %}" class="btn BtnEditar form-control">Editar
          Noticia</a>
      </div>
      <div class="col">
        <a href="{% url 'RH:eliminar_noticias' pk=noticia.id %}" class="btn BtnEliminar form-control">Eliminar
          Noticia</a>
      </div>
      <div class="col">
        <a href="{% url 'RH:lista_noticias' %}" class="btn BtnCancelar form-control">Cancelar</a>
      </div>
    </div>
  </div>
</body>
{% endblock content %}

ADSAP/templates/RH/Noticias/noticia_editar.html
{% extends 'base/base.html'%}
{% block title %}Menú de edicion{% endblock title %}
{% block content %}
<style>
  .background {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 70px;
    padding-left: 25px;
    padding-right: 25px;
    height: 700px;
    width: 1000px;
    margin-left: 300px;
    display: block;
  }

  .Tittle {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 10px;
  }

  .Sub {
    font-size: 2em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: center;
    margin-bottom: 30px;
  }

  .Form{
    font-size: 1.3em;
    font-family: 'ZCOOL QingKe HuangYou';
  }

  .BtnRealizar {
    background-color: #009c0d;
    border-color: #009c0d;
    color: #fff;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnRealizar:hover {
    background-color: #006909;
    color: #fff;
  }

  .BtnCancelar {
    background-color: red;
    border-color: red;
    color: #fff;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnCancelar:hover {
    background-color: rgb(141, 0, 0);
    color: #fff;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="Tittle">ADSAP</p>
    <p class="Sub">Editor de noticias</p>
    <div class="Form">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row">
          <div class="col">
            <button type="submit" class="btn BtnRealizar form-control">Actualizar</button>
          </div>
          <div class="col">
            <a href="{% url 'RH:lista_noticias' %}" class="btn BtnCancelar form-control">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</body>
{% endblock content %}

ADSAP/templates/RH/Noticias/noticia_eliminar.html
{% extends 'base/base.html'%}
{% block title %}Eliminar Noticia{% endblock title %}
{% block content %}
<style>
  .background {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 150px;
    padding-left: 25px;
    padding-right: 25px;
    height: 700px;
    width: 700px;
    border-radius: 20px;
    margin-left: 450px;
    position: relative;
    display: block;
  }

  img {
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    height: 200px;
    width: 200px;
    display: block;
    padding-bottom: 10px;
  }

  .Tittle {
    font-size: 2em;
    font-weight: bold;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: center;
    margin-bottom: 10px;
  }

  .Instrucciones {
    font-size: 1.5em;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: justify;
    margin-bottom: 25px;
  }

  .BtnEliminar {
    background-color: red;
    border-color: red;
    color: #fff;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnEliminar:hover {
    background-color: rgb(141, 0, 0);
    color: #fff;
  }

  .BtnCancelar {
    background-color: orange;
    border-color: orange;
    color: #fff;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnCancelar:hover {
    background-color: rgb(146, 95, 0);
    color: #fff;
  }
</style>

<body class="background">

  <div class=Contenedor>
    <img src="https://cdn-icons-png.flaticon.com/256/2194/2194309.png">
    <p class="Tittle">¿Estás seguro de que deseas eliminar a esta noticia?</p>
    <p class="Instrucciones">Esto eliminará automáticamente la información de la noticia y no podra ser recuperada.</p>
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <button type="submit" class="btn BtnEliminar form-control">Eliminar noticia</button>
        </div>
        <div class="col">
          <a href="{% url 'RH:lista_noticias' %}" class="btn BtnCancelar form-control">Cancelar</a>
        </div>
    </form>
  </div>
</body>
{% endblock content %}

ADSAP/templates/RH/Noticias/noticias.html
{% extends 'base/base.html'%}
{% block title %} Administración de Noticias {% endblock title %}
{% block content %}
<style>
  body {
    background-color: #fff;
  }

  .bd-radius {
    border-radius: 15px;
  }

  .col-lg-4 {
    flex: 0 0 auto;
    width: 33.333333%;
  }

  .row {
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
    gap: 4rem;
  }

  .col-lg-4 {
    flex: 0 0 auto;
    width: auto;
  }

  .btn1 {
    margin-top: 20px;
    margin-bottom: 20px;
    background-color: #004c9759;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .btn1:hover {
    background-color: #004b97b7;
  }

  .btn2 {
    background-color: #003366;
    border-color: #003366;
    font-size: 1.5em;
    width: 750px;
    margin-left: auto;
    margin-right: auto;
    display: block;
  }

  .btn-image {
    display: inline-block;
    padding: 0;
    width: 325px;
    height: 255px;
    text-align: center;
    color: black;
    font-family: 'Arial', sans-serif;
    font-weight: bold;
    border-radius: 15px;
  }

  .btn-image img {
    width: 150px;
    height: 150px;
    object-fit: contain;
    margin-top: 30px;
    margin-bottom: 0px;
  }

  .btn-image span {
    display: block;
    margin-top: 10px;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 100px;
    padding-left: 25px;
    padding-right: 25px;
    height: 700px;
    width: 1000px;
    border-radius: 20px;
    margin-left: 250px;
    display: block;
  }

  .TittleADSAP {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Sub {
    font-size: 2.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: center;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="TittleADSAP">ADSAP</p>
    <p class="Sub">¿Qué acción desea realizar?</p>
    <div class="row">
      <div class="col-lg-4">
        <p>
          <a class="btn btn-secondary btn-image btn1" href="{% url 'RH:crea_noticias' %}">
            <img src="https://cdn-icons-png.flaticon.com/256/1091/1091254.png" alt="Dar de alta empleado">
            <span style="margin-top: 0px; font-size: 1.7em; font-weight: bold;">ALTA NOTICIAS</span>
          </a>
        </p>
      </div>
      <div class="col-lg-4">
        <p>
          <a class="btn btn-secondary btn-image btn1" href="{% url 'RH:lista_noticias' %}">
            <img src="https://cdn-icons-png.flaticon.com/256/10337/10337163.png" alt="Modificar empleado">
            <span style="margin-top: 0px; font-size: 1.7em; font-weight: bold;">MODIFICAR NOTICIAS</span>
          </a>
        </p>
      </div>
    </div>
    <a class="btn btn-primary py-2 btn2" href="{% url 'home:home' %}">Volver al menú</a>
  </div>
</body>
{% endblock content %}

ADSAP/templates/RH/Noticias/noticias_filter.html
{% extends 'base/base.html'%}
{% block title %}Noticias{% endblock title %}
{% block content %}
<style>
  body {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 20px;
    padding-left: 25px;
    padding-right: 25px;
    width: 1300px;
    margin-left: 150px;
    display: block;
  }

  .Filtro {
    padding-bottom: 20px;
  }

  .form-control {
    padding: 20px;
    font-size: 1.5em;
    font-family: 'ZCOOL QingKe HuangYou';
  }

  .TittleADSAP {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Sub {
    font-size: 2.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: center;
  }

  .accordion-button {
    font-size: 0.8em;
  }

  .accordion-body {
    font-size: 1.5em;
    text-align: justify;
  }

  .accordion-collapse {
    padding-bottom: 10px;
  }

  .btn {
    background-color: #003366;
    border-color: #003366;
    font-size: 1.3em;
  }

  img {
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    height: 150px;
    width: 150px;
    display: block;
    padding-bottom: 10px;
  }

  .imgnoticia {
    float: left;
    margin-right: 20px;
    height: 150px;
    width: 150px;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="TittleADSAP">ADSAP</p>
    <p class="Sub">Editar noticias de la empresa</p>
    <div class="Filtro">
      <form action="" method="get">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Buscar noticia" name="busquedaNoticias">
          <button type="submit" class="btn btn-primary" data-mdb-ripple-init>
            <i class="fas fa-search"></i>
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search"
              viewBox="0 0 16 16">
              <path
                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
            </svg>
          </button>
        </div>
      </form>
    </div>
    <div>
      {% for noticia in noticias %}
      <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header" id="heading{{ forloop.counter }}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
              data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseThree">
              {{ noticia.titulo }}
            </button>
          </h2>
          <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse"
            aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <div>
                {% if noticia.imagen %}
                <img class="imgnoticia" src="{{ noticia.imagen.url }}">
                {% else %}
                {% endif %}
                {{ noticia.contenido }}
              </div>
              <br>
              <a href="{% url 'RH:detalles_noticias' pk=noticia.id  %}" class="btn btn-primary py-2">Más opciones</a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <br>
    <a href="{% url 'RH:noticias' %}" class="btn btn-primary">Regresar</a>

</body>
{% endblock content %}