ADSAP/ADSAP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('home/', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('RH/', include("RH.urls")),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADSAP/RH/urls.py
from django.urls import path
from RH import views

app_name = "RH"

urlpatterns = [
    path('empleados/', views.Empleados.as_view(), name="empleados"),
    path('empleados/crea', views.Crea_Empleados.as_view(), name="crea_empleados"),
    path('empleados/crea/<int:user_id>/', views.Crea_Empleados2.as_view(), name="crea_empleados2"),
    path('empleados/editar/', views.Edita_Empleados_Busqueda.as_view(), name="editar_empleado_busqueda"),
    path('empleados/editar/<int:pk>/', views.Empleado_Detalles.as_view(), name='editar_empleados_list'),
    path('empleados/editar/empleado/<int:pk>/', views.Edita_Empleados.as_view(), name='editar_empleado'),
    path('empleados/editar/filtro/', views.Edita_Empleados_List.as_view(), name='empleado_busqueda'),
    path('empleados/editar/empleado/eliminar/<int:pk>/', views.Elimina_Empleados.as_view(), name='eliminar_empleado'),
    path('administra_vacaciones/', views.Vacaciones_Busqueda.as_view(), name="vacaciones_busqueda"),
    path('administra_vacaciones/estado/<int:pk>/', views.Edita_Vacaciones.as_view(), name="vacaciones_estado"),
    path('administra_vacaciones/filtro/', views.searchVacaciones, name="vacaciones_filtro"),
    path('administra_permisos/', views.Permisos_Busqueda.as_view(), name="permisos_busqueda"),
    path('administra_permisos/estado/<int:pk>/', views.Edita_Permisos.as_view(), name="permisos_estado"),
    path('administra_permisos/filtro/', views.searchPermisos, name="permisos_filtro"),
    path('administra_noticas/', views.Noticias.as_view(), name="noticias"),
    path('administra_noticas/crea/', views.Crea_Noticias.as_view(), name="crea_noticias"),
    path('administra_noticas/lista/', views.ListarNoticias.as_view(), name="lista_noticias"),
    path('administra_noticas/detalle/<int:pk>/', views.DetallesNoticia.as_view(), name="detalles_noticias"),
    path('administra_noticas/editar/<int:pk>/', views.Edita_Noticias.as_view(), name="editar_noticias"),
    path('administra_noticas/eliminar/<int:pk>/', views.Elimina_Noticia.as_view(), name="eliminar_noticias"),
    path('administra_noticas/lista/filtro/', views.searchNoticias, name="noticias_filtro"),
    path('administra_faqs/', views.Preguntas.as_view(), name="faqs"),
    path('administra_faqs/crea/', views.Crea_Preguntas.as_view(), name="crea_faqs"),
    path('administra_faqs/lista/', views.ListarPreguntas.as_view(), name="lista_faqs"),
    path('administra_faqs/detalle/<int:pk>/', views.DetallesPregunta.as_view(), name="detalles_faqs"),
    path('administra_faqs/editar/<int:pk>/', views.Edita_Preguntas.as_view(), name="editar_faqs"),
    path('administra_faqs/eliminar/<int:pk>/', views.Elimina_Pregunta.as_view(), name="eliminar_faqs"),
    path('administra_faqs/lista/filtro/', views.searchPreguntas, name="faqs_filtro"),
    path('administra_incapacidades/', views.Incapacidades.as_view(), name="incapacidades"),
    path('administra_incapacidades/detalle/<int:pk>/', views.Incapacidades_Detalles.as_view(), name="incapacidad_detalle"),
    path('administra_incapacidades/filtro/', views.searchIncapacidades, name="busqueda_incapacidades"),
    path('tabla_nominas/', views.crea_semana_nominas, name='crea_semana'),
    path('reportes/actualiza/<int:pk>/', views.Edita_Reportes.as_view(), name='reportes_actualiza'),
]

ADSAP/core/urls.py
from django.urls import path, re_path
from core import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "core"

urlpatterns = [
    path('faq/', views.Preguntas.as_view(), name="faq"),
    path('faq/filtro', views.searchPreguntas, name="faq_filter"),
    path('noticias/', views.Noticias.as_view(), name="noticias"),
    path('noticias/filtro', views.searchNoticias, name="noticias_filter"),
    path('datos_personales', views.Datos_Personales.as_view(), name="datos_personales"),
    path('vacaciones', views.Vacaciones.as_view(), name="vacaciones"),
    path('vacaciones/filtro', views.searchVacaciones, name="vacaciones_filter"),
    path('vacaciones/solicitud', views.Vacaciones_Form, name="vacaciones_solicitud"),
    path('vacaciones/solicitud/confirmacion', views.Vacaciones_Confirmacion.as_view(), name="vacaciones_confirmacion"),
    path('vacaciones/solicitud/estado/<int:pk>/', views.Vacaciones_Estado.as_view(), name="vacaciones_estado"),
    path('vacaciones/solicitud/eliminar/<int:pk>/', views.Vacaciones_Eliminacion.as_view(), name="vacaciones_eliminar_confirmacion"),
    path('permisos', views.Permisos.as_view(), name="permisos"),
    path('permisos/solicitud', views.Permisos_Form, name="permisos_solicitud"),
    path('permisos/solicitud/confirmacion', views.Permisos_Confirmacion.as_view(), name="permisos_confirmacion"),
    path('permisos/solicitud/estado/<int:pk>/', views.Permisos_Estado.as_view(), name="permisos_estado"),
    path('permisos/solicitud/eliminar/<int:pk>/', views.Permisos_Eliminacion.as_view(), name="permisos_eliminar_confirmacion"),
    path('permisos/filtro', views.searchPermisos, name="permisos_filter"),
    path('incapacidades', views.Incapacidades.as_view(), name="incapacidades"),
    path('incapacidades/detalle/<int:pk>/', views.Incapacidades_Detalles.as_view(), name="incapacidad_detalle"),
    path('incapacidades/solicitud', views.Incapacidades_Form, name="incapacidades_solicitud"),
    path('incapacidades/filtro', views.searchIncapacidades, name="incapacidades_filter"),
    path('reporte_error', views.Reportes.as_view(), name="reporte_error"),
    path('reporte_error/genera', views.Genera_Reporte.as_view(), name="genera_reporte"),
    path('reporte_error/lista/', views.Lista_Reportes.as_view(), name="reporte_lista"),
    path('reporte_error/detalle/<int:pk>/', views.Reporte_Estado.as_view(), name="reporte_detalle"),
    path('reporte_error/lista/filtro/', views.searchReportes, name="reporte_filtro"),
    path('nominas/', views.Nominas.as_view(), name="nominas"),
    path('nominas/filtro', views.searchNominas, name="nominas_filter"),
    path('nominas/detalle/<int:pk>/', views.Nominas_Detalle.as_view(), name="nomina_detalle"),
    path('nominas/nomina_pdf/<int:nomina_id>/', views.generar_reporte_pdf, name='generar_reporte_nomina'),
    




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADSAP/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('home/', views.Home.as_view(), name="home"),
    path('cuenta/', views.Cuenta.as_view(), name="cuenta"),

]

ADSAP/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <title>{% block title %}{% endblock title %}</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <style>
    body {
      max-width: 100%;
      margin: 0 auto;
      overflow-x: hidden;
    }

    .bg-color {
      background-color: #083464;
    }

    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }

    .col-lg-2 {
      position: fixed;
      width: 310px;
      left: 0;
      top: 0;
      bottom: 0;
      overflow-y: auto;
      padding-left: 0;

    }

    .col-lg-9 {
      margin-left: 300px;
    }

    .empleado {
      white-space: nowrap;
      overflow-wrap: normal;
    }

    .Btn {
      cursor: pointer;
      transition: background-color 0.3s;
    }

    .Btn:hover {
      background-color: #005fbebe;
    }
  </style>

  <link href="{% static 'css/sidebars.css' %}" rel="stylesheet">
</head>

<body>

  <div class="row">
    <div class="col-lg-2">
      <!-- Sidebar -->
      <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="question" viewBox="0 0 16 16">
          <path
            d="M14.897 1a4 4 0 0 1 2.664 1.016l.165 .156l4.1 4.1a4 4 0 0 1 1.168 2.605l.006 .227v5.794a4 4 0 0 1 -1.016 2.664l-.156 .165l-4.1 4.1a4 4 0 0 1 -2.603 1.168l-.227 .006h-5.795a3.999 3.999 0 0 1 -2.664 -1.017l-.165 -.156l-4.1 -4.1a4 4 0 0 1 -1.168 -2.604l-.006 -.227v-5.794a4 4 0 0 1 1.016 -2.664l.156 -.165l4.1 -4.1a4 4 0 0 1 2.605 -1.168l.227 -.006h5.793zm-2.897 14a1 1 0 0 0 -.993 .883l-.007 .117l.007 .127a1 1 0 0 0 1.986 0l.007 -.117l-.007 -.127a1 1 0 0 0 -.993 -.883zm1.368 -6.673a2.98 2.98 0 0 0 -3.631 .728a1 1 0 0 0 1.44 1.383l.171 -.18a.98 .98 0 0 1 1.11 -.15a1 1 0 0 1 -.34 1.886l-.232 .012a1 1 0 0 0 .111 1.994a3 3 0 0 0 1.371 -5.673z"
            stroke-width="0" fill="currentColor" />
        </symbol>
        <symbol id="home" viewBox="0 0 16 16">
          <path
            d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z" />
        </symbol>
        <symbol id="speedometer2" viewBox="0 0 16 16">
          <path
            d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z" />
          <path fill-rule="evenodd"
            d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z" />
        </symbol>
        <symbol id="table" viewBox="0 0 16 16">
          <path
            d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z" />
        </symbol>
        <symbol id="people-circle" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
          <path fill-rule="evenodd"
            d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
        </symbol>
        <symbol id="grid" viewBox="0 0 16 16">
          <path
            d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z" />
        </symbol>
      </svg>

      <main class="d-flex flex-nowrap ">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-color" style="width: 300px;">
          <a href="{% url 'home:home' %}"
            class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none"
            style="padding-left: 30px;">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-building"
              viewBox="0 0 16 16">
              <path
                d="M4 2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zM4 5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM7.5 5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM4.5 8a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5z" />
              <path
                d="M2 1a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1zm11 0H3v14h3v-2.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V15h3z" />
            </svg>
            <span class="fs-1" style="padding-left: 20px;"> ADSAP</span>
          </a>
          <hr style="color: white;">
          <p class="text-white " style="font-size: large; margin-bottom: 0px;"> <b>Nombre de la empresa:</b> </p>
          <p class="text-white"> {{ empleado_empresa }} </p>
          <p class="text-white" style="font-size: large; margin-bottom: 0px;"><b>Nombre del empleado:</b> </p>
          <div class="empleado">

            <span class="text-white">{{ empleado_nombre }}</span>
            <span class="text-white">{{ empleado_apellido_paterno }}</span>
            <span class="text-white">{{ empleado_apellido_materno }}</span>
          </div>
          <hr style="color: white;">
          <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
              <a href="{% url 'home:home' %}" class="nav-link text-white Btn" aria-current="page">
                <svg class="bi pe-none me-2" width="16" height="16">
                  <use xlink:href="#home" />
                </svg>
                Inicio
              </a>
            </li>
            <li>
              {% if 'Personal RH' in grupos_usuario %}
              <a href="{% url 'RH:faqs' %}" class="nav-link text-white Btn">
                {% else %}
                <a href="{% url 'core:faq' %}" class="nav-link text-white Btn">
                  {% endif %}

                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-patch-question-fill" viewBox="0 0 16 16">
                    <path
                      d="M5.933.87a2.89 2.89 0 0 1 4.134 0l.622.638.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01zM7.002 11a1 1 0 1 0 2 0 1 1 0 0 0-2 0m1.602-2.027c.04-.534.198-.815.846-1.26.674-.475 1.05-1.09 1.05-1.986 0-1.325-.92-2.227-2.262-2.227-1.02 0-1.792.492-2.1 1.29A1.7 1.7 0 0 0 6 5.48c0 .393.203.64.545.64.272 0 .455-.147.564-.51.158-.592.525-.915 1.074-.915.61 0 1.03.446 1.03 1.084 0 .563-.208.885-.822 1.325-.619.433-.926.914-.926 1.64v.111c0 .428.208.745.585.745.336 0 .504-.24.554-.627" />
                  </svg>   Preguntas Frecuentes
                </a>

                <a href="{% url 'core:reporte_error' %}" class="nav-link text-white Btn" aria-current="page">
                  Reportar un error
                </a>

                <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="nav-link text-white Btn" aria-current="page">
                    Salir del sistema</button>
                </form>
            </li>
          </ul>
        </div>
      </main>
      <!-- End Sidebar -->
    </div>
    <div class="col-lg-9">
      <div class="row">
        <div class="col">
          <!-- Contenido principal -->
          {% block content %}
          {% endblock content %}
        </div>
      </div>
    </div>
  </div>




  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/sidebars.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"
    integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
    crossorigin="anonymous"></script>
</body>

</html>