ADSAP/ADSAP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('home/', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('RH/', include("RH.urls")),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADSAP/RH/urls.py
from django.urls import path
from RH import views

app_name = "RH"

urlpatterns = [
    path('empleados/', views.Empleados.as_view(), name="empleados"),
    path('empleados/crea', views.Crea_Empleados.as_view(), name="crea_empleados"),
    path('empleados/crea/<int:user_id>/', views.Crea_Empleados2.as_view(), name="crea_empleados2"),
    path('empleados/editar/', views.Edita_Empleados_Busqueda.as_view(), name="editar_empleado_busqueda"),
    path('empleados/editar/<int:pk>/', views.Empleado_Detalles.as_view(), name='editar_empleados_list'),
    path('empleados/editar/empleado/<int:pk>/', views.Edita_Empleados.as_view(), name='editar_empleado'),
    path('empleados/editar/filtro/', views.Edita_Empleados_List.as_view(), name='empleado_busqueda'),
    path('empleados/editar/empleado/eliminar/<int:pk>/', views.Elimina_Empleados.as_view(), name='eliminar_empleado'),
    path('administra_vacaciones/', views.Vacaciones_Busqueda.as_view(), name="vacaciones_busqueda"),
    path('administra_vacaciones/estado/<int:pk>/', views.Edita_Vacaciones.as_view(), name="vacaciones_estado"),
    path('administra_vacaciones/filtro/', views.searchVacaciones, name="vacaciones_filtro"),
    path('administra_permisos/', views.Permisos_Busqueda.as_view(), name="permisos_busqueda"),
    path('administra_permisos/estado/<int:pk>/', views.Edita_Permisos.as_view(), name="permisos_estado"),
    path('administra_permisos/filtro/', views.searchPermisos, name="permisos_filtro"),
    path('administra_noticas/', views.Noticias.as_view(), name="noticias"),
    path('administra_noticas/crea/', views.Crea_Noticias.as_view(), name="crea_noticias"),
    path('administra_noticas/lista/', views.ListarNoticias.as_view(), name="lista_noticias"),
    path('administra_noticas/detalle/<int:pk>/', views.DetallesNoticia.as_view(), name="detalles_noticias"),
    path('administra_noticas/editar/<int:pk>/', views.Edita_Noticias.as_view(), name="editar_noticias"),
    path('administra_noticas/eliminar/<int:pk>/', views.Elimina_Noticia.as_view(), name="eliminar_noticias"),
    path('administra_noticas/lista/filtro/', views.searchNoticias, name="noticias_filtro"),
    path('administra_faqs/', views.Preguntas.as_view(), name="faqs"),
    path('administra_faqs/crea/', views.Crea_Preguntas.as_view(), name="crea_faqs"),
    path('administra_faqs/lista/', views.ListarPreguntas.as_view(), name="lista_faqs"),
    path('administra_faqs/detalle/<int:pk>/', views.DetallesPregunta.as_view(), name="detalles_faqs"),
    path('administra_faqs/editar/<int:pk>/', views.Edita_Preguntas.as_view(), name="editar_faqs"),
    path('administra_faqs/eliminar/<int:pk>/', views.Elimina_Pregunta.as_view(), name="eliminar_faqs"),
    path('administra_faqs/lista/filtro/', views.searchPreguntas, name="faqs_filtro"),
    path('administra_incapacidades/', views.Incapacidades.as_view(), name="incapacidades"),
    path('administra_incapacidades/detalle/<int:pk>/', views.Incapacidades_Detalles.as_view(), name="incapacidad_detalle"),
    path('administra_incapacidades/filtro/', views.searchIncapacidades, name="busqueda_incapacidades"),
    path('tabla_nominas/', views.crea_semana_nominas, name='crea_semana'),
    path('reportes/actualiza/<int:pk>/', views.Edita_Reportes.as_view(), name='reportes_actualiza'),
]

ADSAP/core/urls.py
from django.urls import path, re_path
from core import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "core"

urlpatterns = [
    path('faq/', views.Preguntas.as_view(), name="faq"),
    path('faq/filtro', views.searchPreguntas, name="faq_filter"),
    path('noticias/', views.Noticias.as_view(), name="noticias"),
    path('noticias/filtro', views.searchNoticias, name="noticias_filter"),
    path('datos_personales', views.Datos_Personales.as_view(), name="datos_personales"),
    path('vacaciones', views.Vacaciones.as_view(), name="vacaciones"),
    path('vacaciones/filtro', views.searchVacaciones, name="vacaciones_filter"),
    path('vacaciones/solicitud', views.Vacaciones_Form, name="vacaciones_solicitud"),
    path('vacaciones/solicitud/confirmacion', views.Vacaciones_Confirmacion.as_view(), name="vacaciones_confirmacion"),
    path('vacaciones/solicitud/estado/<int:pk>/', views.Vacaciones_Estado.as_view(), name="vacaciones_estado"),
    path('vacaciones/solicitud/eliminar/<int:pk>/', views.Vacaciones_Eliminacion.as_view(), name="vacaciones_eliminar_confirmacion"),
    path('permisos', views.Permisos.as_view(), name="permisos"),
    path('permisos/solicitud', views.Permisos_Form, name="permisos_solicitud"),
    path('permisos/solicitud/confirmacion', views.Permisos_Confirmacion.as_view(), name="permisos_confirmacion"),
    path('permisos/solicitud/estado/<int:pk>/', views.Permisos_Estado.as_view(), name="permisos_estado"),
    path('permisos/solicitud/eliminar/<int:pk>/', views.Permisos_Eliminacion.as_view(), name="permisos_eliminar_confirmacion"),
    path('permisos/filtro', views.searchPermisos, name="permisos_filter"),
    path('incapacidades', views.Incapacidades.as_view(), name="incapacidades"),
    path('incapacidades/detalle/<int:pk>/', views.Incapacidades_Detalles.as_view(), name="incapacidad_detalle"),
    path('incapacidades/solicitud', views.Incapacidades_Form, name="incapacidades_solicitud"),
    path('incapacidades/filtro', views.searchIncapacidades, name="incapacidades_filter"),
    path('reporte_error', views.Reportes.as_view(), name="reporte_error"),
    path('reporte_error/genera', views.Genera_Reporte.as_view(), name="genera_reporte"),
    path('reporte_error/lista/', views.Lista_Reportes.as_view(), name="reporte_lista"),
    path('reporte_error/detalle/<int:pk>/', views.Reporte_Estado.as_view(), name="reporte_detalle"),
    path('reporte_error/lista/filtro/', views.searchReportes, name="reporte_filtro"),
    path('nominas/', views.Nominas.as_view(), name="nominas"),
    path('nominas/filtro', views.searchNominas, name="nominas_filter"),
    path('nominas/detalle/<int:pk>/', views.Nominas_Detalle.as_view(), name="nomina_detalle"),
    path('nominas/nomina_pdf/<int:nomina_id>/', views.generar_reporte_pdf, name='generar_reporte_nomina'),
    




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ADSAP/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('home/', views.Home.as_view(), name="home"),
    path('cuenta/', views.Cuenta.as_view(), name="cuenta"),

]

ADSAP/templates/reporte/error_form.html
{% extends 'base/base.html'%}
{% block title %}Menú de edicion{% endblock title %}
{% block content %}
<style>
  .background {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 70px;
    padding-left: 25px;
    padding-right: 25px;
    width: 900px;
    margin-left: 400px;
    display: block;
  }

  .Tittle {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 10px;
  }

  .Sub {
    font-size: 2em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: center;
    margin-bottom: 30px;
  }

  .Sub1 {
    font-size: 2em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: justify;
    margin-bottom: 30px;
  }

  .Form{
    font-size: 1.3em;
    font-family: 'ZCOOL QingKe HuangYou';
  }

  .BtnRealizar {
    background-color: #009c0d;
    border-color: #009c0d;
    color: #fff;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnRealizar:hover {
    background-color: #006909;
    color: #fff;
  }

  .BtnCancelar {
    background-color: red;
    border-color: red;
    color: #fff;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnCancelar:hover {
    background-color: rgb(141, 0, 0);
    color: #fff;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="Tittle">ADSAP</p>
    <p class="Sub">Enviar reporte de error</p>
    <p class="Sub1">Agregar datos del problema</p>
    <div class="Form">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="row">
          <div class="col">
            <button type="submit" class="btn BtnRealizar form-control">Enviar Reporte</button>
          </div>
          <div class="col">
            <a href="{% url 'core:reporte_error' %}" class="btn BtnCancelar form-control">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</body>
{% endblock content %}

ADSAP/templates/reporte/reporte_error.html
{% extends 'base/base.html'%}
{% block title %} Reporte de error {% endblock title %}
{% block content %}
<style>
  body {
    background-color: #fff;
  }

  .bd-radius {
    border-radius: 15px;
  }

  .col-lg-4 {
    flex: 0 0 auto;
    width: 33.333333%;
  }

  .row {
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
    gap: 4rem;
  }

  .col-lg-4 {
    flex: 0 0 auto;
    width: auto;
  }

  .btn1 {
    margin-top: 20px;
    margin-bottom: 20px;
    background-color: #004c9759;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .btn1:hover {
    background-color: #004b97b7;
  }

  .btn2 {
    background-color: #003366;
    border-color: #003366;
    font-size: 1.5em;
    width: 750px;
    margin-left: auto;
    margin-right: auto;
    display: block;
  }

  .btn-image {
    display: inline-block;
    padding: 0;
    width: 325px;
    height: 255px;
    text-align: center;
    color: black;
    font-family: 'Arial', sans-serif;
    font-weight: bold;
    border-radius: 15px;
  }

  .btn-image img {
    width: 150px;
    height: 150px;
    object-fit: contain;
    margin-top: 15px;
    margin-bottom: 0px;
  }

  .btn-image span {
    display: block;
    margin-top: 10px;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 100px;
    padding-left: 25px;
    padding-right: 25px;
    height: 700px;
    width: 1000px;
    border-radius: 20px;
    margin-left: 250px;
    display: block;
  }

  .TittleADSAP {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Sub {
    font-size: 2.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: center;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="TittleADSAP">ADSAP</p>
    <p class="Sub">¿Qué acción desea realizar?</p>
    <div class="row">
      <div class="col-lg-4">
        <p>
          <a class="btn btn-secondary btn-image btn1" href="{% url 'core:genera_reporte' %}">
            <img src="https://cdn-icons-png.flaticon.com/256/11696/11696675.png" alt="Dar de alta empleado">
            <span style="margin-top: -2px; font-size: 1.7em; font-weight: bold;">Enviar reporte </span>
          </a>
        </p>
      </div>
      <div class="col-lg-4">
        <p>
          <a class="btn btn-secondary btn-image btn1" href="{% url 'core:reporte_lista' %}">
            <img src="https://cdn-icons-png.flaticon.com/256/2874/2874802.png" alt="Modificar empleado">
            <span style="margin-top: -2px; font-size: 1.7em; font-weight: bold;">Ver reportes enviados</span>
          </a>
        </p>
      </div>
    </div>
    <a class="btn btn-primary py-2 btn2" href="{% url 'home:home' %}">Volver al menú</a>
  </div>
</body>
{% endblock content %}

ADSAP/templates/reporte/reporte_estado.html
{% extends 'base/base.html'%}
{% load static %}
{% block title %}Estado Solicitud{% endblock title %}
{% block content %}
<style>
  .background {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 50px;
    padding-left: 60px;
    padding-right: 60px;
    height: 700px;
    width: 1000px;
    border-radius: 20px;
    margin-left: 300px;
    display: block;
  }

  .Tittle {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 30px;
  }

  .Sub {
    font-size: 2em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: left;
    font-weight: bold;
    margin-top: 30px;
    margin-bottom: 5px;
  }

  .Estado {
    font-size: 2em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: left;
    font-weight: bold;
  }

  .EstadoDato {
    font-size: 30px;
    color: #000;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: left;
    font-weight: bold;
    margin-top: 30px;
  }

  img {
    float: left;
    margin-right: 10px;
    height: 150px;
    width: 150px;
  }

  .Datos {
    font-size: 1.8em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    margin-bottom: 0px;
  }

  .DatosUsuario {
    font-size: 24px;
    color: #000000;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
  }

  .BtnAtras {
    background-color: #003366;
    border-color: #003366;
    font-size: 1.5em;
    margin-top: 30px;
  }
</style>

<body class="background">
  <div class=Contenedor>
    <p class="Tittle">Estado del reporte</p>
    <p class="Estado">Estado: <span class="EstadoDato">{{ reporte.estado }}</span></p>
    <p class="Sub">Datos del reporte</p>
    <p class="Datos">Seccion: <span class="DatosUsuario">{{ reporte.seccion }} </span></p>
    <p class="Datos">Fecha envio reporte: <span class="DatosUsuario">{{ reporte.fecha_inicio }}</span></p>
    <p class="Datos">Fecha fin reporte: <span class="DatosUsuario">{{ reporte.fecha_fin }}</span></p>
    <p class="Datos">Descripcion: <span class="DatosUsuario">{{ reporte.descripcion }}</span></p>
    <p class="Datos">Imagen:</p>
    {% if reporte.imagen %}
    <img src="{{ reporte.imagen.url }}" alt="Imagen de reporte">
    {% else %}
    <p class="DatosUsuario">No se ha subido una imagen para este reporte</p>
    {% endif %}
    <a class="btn btn-primary py-2 BtnAtras" type="" href="{% url 'core:reporte_lista' %}">Volver a reportes</a>
  </div>
</body>
{% endblock content %}

ADSAP/templates/reporte/reporte_filter.html
{% extends 'base/base.html'%}
{% block title %}Reportes de error{% endblock title %}
{% block content %}
<style>
  .background {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 50px;
    padding-left: 25px;
    padding-right: 25px;
    height: 700px;
    width: 1000px;
    border-radius: 20px;
    margin-left: 300px;
    display: block;
  }

  img {
    height: 50px;
    width: 50px;
  }

  .btn1{
    margin-top: -10px;
    font-size: 1.1em;
  }

  .Tittle {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Sub {
    font-size: 2.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: left;
    position: absolute;
  }

  .btn {
    background-color: #003366;
    border-color: #003366;
    font-size: 1.5em;
  }

  .Filtro {
    padding-bottom: 20px;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="Tittle">Reportes enviados</p>

    <div class="Filtro">
      <form action="" method="get">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Buscar reportes" name="busquedaReportes">
          <button type="submit" class="btn btn-primary" data-mdb-ripple-init>
            <i class="fas fa-search"></i>
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search"
              viewBox="0 0 16 16">
              <path
                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
            </svg>
          </button>
        </div>
      </form>
    </div>
    <div class="Respuestas">
        {% for reporte in reportes %}
        <div class="list-group">
          <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3 vacaciones" aria-current="true">
            <img src="https://cdn-icons-png.flaticon.com/256/4673/4673277.png">
            <div>
              <p class="mb-0">Seccion: {{ reporte.seccion }} </p>
              <p class="mb-0">Fecha envio reporte: {{ reporte.fecha_inicio }}  </p>
            </div>
          </a>
          <a href="{% url 'core:reporte_detalle' pk=reporte.id %}" class="btn btn-primary py-2 btn1">Estado Reporte</a>
        </div>
        {% endfor %}
    </div>
    <br>
    <a class="btn btn-primary py-2 Btn1" href="{% url 'core:reporte_error' %}">Volver a reportes</a>
</body>
{% endblock content %}

ADSAP/templates/reporte/reportes_list.html
{% extends 'base/base.html'%}
{% block title %}Reportes de error{% endblock title %}
{% block content %}
<style>
  .background {
    background-color: #fff;
  }

  .Contenedor {
    background-color: #fff;
    padding-top: 50px;
    padding-left: 25px;
    padding-right: 25px;
    height: 700px;
    width: 1000px;
    border-radius: 20px;
    margin-left: 300px;
    display: block;
  }

  img {
    height: 50px;
    width: 50px;
  }

  .btn1{
    margin-top: -10px;
    font-size: 1.1em;
  }

  .Tittle {
    font-size: 3em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    font-weight: bold;
    text-align: center;
    margin-bottom: 0;
  }

  .Sub {
    font-size: 2.5em;
    color: #003366;
    font-family: 'ZCOOL QingKe HuangYou';
    text-align: left;
    position: absolute;
  }

  .btn {
    background-color: #003366;
    border-color: #003366;
    font-size: 1.5em;
  }

  .Filtro {
    padding-bottom: 20px;
  }
</style>

<body>
  <div class="Contenedor">
    <p class="Tittle">Reportes enviados</p>

    <div class="Filtro">
      <form action="filtro" method="get">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Buscar reportes" name="busquedaReportes">
          <button type="submit" class="btn btn-primary" data-mdb-ripple-init>
            <i class="fas fa-search"></i>
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search"
              viewBox="0 0 16 16">
              <path
                d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
            </svg>
          </button>
        </div>
      </form>
    </div>
    <div class="Respuestas">
      {% for reporte in reportes %}
      <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3 vacaciones" aria-current="true">
          <img src="https://cdn-icons-png.flaticon.com/256/4673/4673277.png">
          <div>
            <p class="mb-0">Seccion: {{ reporte.seccion }} </p>
            <p class="mb-0">Fecha envio reporte: {{ reporte.fecha_inicio }}  </p>
          </div>
        </a>
        <a href="{% url 'core:reporte_detalle' pk=reporte.id %}" class="btn btn-primary py-2 btn1">Estado reporte</a>
      </div>
      {% endfor %}
    </div>
    <br>
    <a class="btn btn-primary py-2 Btn1" href="{% url 'core:reporte_error' %}">Volver a reportes</a>
</body>
{% endblock content %}